set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]

set_property PACKAGE_PIN M2 [get_ports IIC_0_0_sda_io]
set_property PACKAGE_PIN M1 [get_ports IIC_0_0_scl_io]
set_property IOSTANDARD LVCMOS18 [get_ports IIC_0_0_scl_io]
set_property IOSTANDARD LVCMOS18 [get_ports IIC_0_0_sda_io]

set_property PACKAGE_PIN AB16 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]

set_property PACKAGE_PIN G7 [get_ports {FP_LEDS_0[0]}]
set_property PACKAGE_PIN G8 [get_ports {FP_LEDS_0[1]}]
set_property PACKAGE_PIN G2 [get_ports {FP_LEDS_0[2]}]
set_property PACKAGE_PIN G3 [get_ports {FP_LEDS_0[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {FP_LEDS_0[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {FP_LEDS_0[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {FP_LEDS_0[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {FP_LEDS_0[0]}]
set_property PACKAGE_PIN B4 [get_ports LTC2195_DCO_P_0]
set_property IOSTANDARD LVDS_25 [get_ports LTC2195_DCO_P_0]
set_property IOSTANDARD LVDS_25 [get_ports LTC2195_DCO_N_0]
set_property PACKAGE_PIN B2 [get_ports LTC2195_FR_P_0]
set_property IOSTANDARD LVDS_25 [get_ports LTC2195_FR_P_0]
set_property IOSTANDARD LVDS_25 [get_ports LTC2195_FR_N_0]
set_property PACKAGE_PIN F7 [get_ports {LTC2195_D0_P_0[0]}]
set_property PACKAGE_PIN B7 [get_ports {LTC2195_D0_P_0[1]}]
set_property PACKAGE_PIN E4 [get_ports {LTC2195_D0_P_0[2]}]
set_property PACKAGE_PIN D1 [get_ports {LTC2195_D0_P_0[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D0_P_0[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D0_N_0[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D0_P_0[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D0_N_0[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D0_P_0[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D0_N_0[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D0_P_0[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D0_N_0[0]}]
set_property PACKAGE_PIN A2 [get_ports {LTC2195_D1_P_0[0]}]
set_property PACKAGE_PIN D5 [get_ports {LTC2195_D1_P_0[1]}]
set_property PACKAGE_PIN F2 [get_ports {LTC2195_D1_P_0[2]}]
set_property PACKAGE_PIN D7 [get_ports {LTC2195_D1_P_0[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D1_P_0[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D1_N_0[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D1_P_0[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D1_N_0[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D1_P_0[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D1_N_0[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D1_P_0[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {LTC2195_D1_N_0[0]}]
set_property PACKAGE_PIN Y14 [get_ports CLK_100_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_100_0]
set_property PACKAGE_PIN V11 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN U13 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN AA14 [get_ports {GPIO_0_0_tri_io[3]}]
set_property PACKAGE_PIN AA15 [get_ports {GPIO_0_0_tri_io[4]}]
set_property PACKAGE_PIN AA12 [get_ports {GPIO_0_0_tri_io[5]}]
set_property PACKAGE_PIN G4 [get_ports {GPIO_0_0_tri_io[6]}]
set_property PACKAGE_PIN AB11 [get_ports {GPIO_0_0_tri_io[7]}]
set_property PACKAGE_PIN F4 [get_ports {GPIO_0_0_tri_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[8]}]

set_property PACKAGE_PIN M7 [get_ports {GPIO_0_0_tri_io[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_0_tri_io[9]}]

set_property PACKAGE_PIN J5 [get_ports o_mosi_0]
set_property PACKAGE_PIN J1 [get_ports o_sclk_0]
set_property IOSTANDARD LVCMOS18 [get_ports o_mosi_0]
set_property IOSTANDARD LVCMOS18 [get_ports o_sclk_0]

create_clock -period 10.000 -name CLK_100 -waveform {0.000 5.000} [get_ports CLK_100_0]
create_clock -period 5.000 -name LTC2195_DCO -waveform {0.000 2.500} [get_ports LTC2195_DCO_P_0]



set_property PACKAGE_PIN T1 [get_ports {GPIO_0_0_tri_io[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_0_tri_io[10]}]

set_property PACKAGE_PIN U14 [get_ports {GPIO_0_0_tri_io[11]}]
set_property PACKAGE_PIN AB12 [get_ports {GPIO_0_0_tri_io[12]}]
set_property PACKAGE_PIN W11 [get_ports {GPIO_0_0_tri_io[13]}]
set_property PACKAGE_PIN U11 [get_ports {GPIO_0_0_tri_io[14]}]
set_property PACKAGE_PIN T17 [get_ports {GPIO_0_0_tri_io[15]}]
set_property PACKAGE_PIN AA11 [get_ports {GPIO_0_0_tri_io[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[11]}]

set_property PACKAGE_PIN V19 [get_ports {GPIO_0_0_tri_io[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[17]}]
set_property PACKAGE_PIN AA19 [get_ports {GPIO_0_0_tri_io[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[18]}]
set_property PACKAGE_PIN AB21 [get_ports {GPIO_0_0_tri_io[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[19]}]

set_property PACKAGE_PIN W18 [get_ports {GPIO_0_0_tri_io[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[20]}]
set_property PACKAGE_PIN W17 [get_ports {GPIO_0_0_tri_io[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[21]}]
set_property PACKAGE_PIN AB19 [get_ports {GPIO_0_0_tri_io[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[22]}]
set_property PACKAGE_PIN AB18 [get_ports {GPIO_0_0_tri_io[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[23]}]
set_property PACKAGE_PIN U19 [get_ports {GPIO_0_0_tri_io[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[24]}]
set_property PACKAGE_PIN K5 [get_ports i_miso_main_0]
set_property IOSTANDARD LVCMOS18 [get_ports i_miso_main_0]
set_property PACKAGE_PIN Y18 [get_ports i_miso_aux_a_0]
set_property IOSTANDARD LVCMOS33 [get_ports i_miso_aux_a_0]
set_property PACKAGE_PIN AA16 [get_ports i_miso_aux_b_0]
set_property IOSTANDARD LVCMOS33 [get_ports i_miso_aux_b_0]
set_property PACKAGE_PIN Y19 [get_ports o_ss_aux_0]
set_property IOSTANDARD LVCMOS33 [get_ports o_ss_aux_0]
set_property PACKAGE_PIN AB22 [get_ports o_sclk_aux_0]
set_property IOSTANDARD LVCMOS33 [get_ports o_sclk_aux_0]
set_property PACKAGE_PIN J2 [get_ports o_ss_main_0]
set_property IOSTANDARD LVCMOS18 [get_ports o_ss_main_0]



set_property PACKAGE_PIN U17 [get_ports o_mosi_aux_dac]
set_property PACKAGE_PIN V18 [get_ports o_sclk_aux_dac]
set_property PACKAGE_PIN K3 [get_ports o_sclk_main_dac]
set_property PACKAGE_PIN AA20 [get_ports o_ss_aux_dac]
set_property PACKAGE_PIN R3 [get_ports o_ss_main_dac]
set_property PACKAGE_PIN R2 [get_ports sdio_main_dac]
set_property PACKAGE_PIN U18 [get_ports i_miso_aux_dac]
set_property IOSTANDARD LVCMOS33 [get_ports i_miso_aux_dac]
set_property IOSTANDARD LVCMOS33 [get_ports o_mosi_aux_dac]
set_property IOSTANDARD LVCMOS33 [get_ports o_sclk_aux_dac]
set_property IOSTANDARD LVCMOS18 [get_ports o_sclk_main_dac]
set_property IOSTANDARD LVCMOS33 [get_ports o_ss_aux_dac]
set_property IOSTANDARD LVCMOS18 [get_ports o_ss_main_dac]
set_property IOSTANDARD LVCMOS18 [get_ports sdio_main_dac]

set_property PACKAGE_PIN T2 [get_ports {AD9117_D_0[0]}]
set_property PACKAGE_PIN U2 [get_ports {AD9117_D_0[1]}]
set_property PACKAGE_PIN M4 [get_ports {AD9117_D_0[2]}]
set_property PACKAGE_PIN M3 [get_ports {AD9117_D_0[3]}]
set_property PACKAGE_PIN P5 [get_ports {AD9117_D_0[13]}]
set_property PACKAGE_PIN R5 [get_ports {AD9117_D_0[12]}]
set_property PACKAGE_PIN N1 [get_ports {AD9117_D_0[11]}]
set_property PACKAGE_PIN N4 [get_ports {AD9117_D_0[10]}]
set_property PACKAGE_PIN L2 [get_ports {AD9117_D_0[9]}]
set_property PACKAGE_PIN P6 [get_ports {AD9117_D_0[8]}]
set_property PACKAGE_PIN N3 [get_ports {AD9117_D_0[7]}]
set_property PACKAGE_PIN R4 [get_ports {AD9117_D_0[6]}]
set_property PACKAGE_PIN P1 [get_ports {AD9117_D_0[5]}]
set_property PACKAGE_PIN L1 [get_ports {AD9117_D_0[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9117_D_0[0]}]
set_property PACKAGE_PIN U1 [get_ports AD9117_DCLKIO_0]
set_property IOSTANDARD LVCMOS18 [get_ports AD9117_DCLKIO_0]

set_property PACKAGE_PIN L5 [get_ports {GPIO_0_0_tri_io[25]}]
set_property PACKAGE_PIN L4 [get_ports {GPIO_0_0_tri_io[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_0_tri_io[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_0_0_tri_io[25]}]

set_property PACKAGE_PIN J7 [get_ports FPGA_CLK1_P_0]
set_property IOSTANDARD LVDS_25 [get_ports FPGA_CLK1_P_0]


create_clock -period 10.000 -name FPGA_DAC_CLK -waveform {0.000 5.000} [get_ports FPGA_CLK1_P_0]
create_clock -period 10.000 -name DCLKIO -waveform {0.000 5.000} [get_ports -filter { NAME =~  "*DCLK*" && DIRECTION == "OUT" }]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets design_1_i/FastServoTop_0/inst/clocks/dac_clk_inst/clk_in1]

set_property PACKAGE_PIN Y15 [get_ports {GPIO_0_0_tri_io[27]}]
set_property PACKAGE_PIN AB14 [get_ports {GPIO_0_0_tri_io[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[28]}]
set_property PACKAGE_PIN AB13 [get_ports {GPIO_0_0_tri_io[29]}]
set_property PACKAGE_PIN V13 [get_ports {GPIO_0_0_tri_io[30]}]
set_property PACKAGE_PIN V14 [get_ports {GPIO_0_0_tri_io[31]}]
set_property PACKAGE_PIN V15 [get_ports {GPIO_0_0_tri_io[32]}]
set_property PACKAGE_PIN U12 [get_ports {GPIO_0_0_tri_io[33]}]
set_property PACKAGE_PIN W13 [get_ports {GPIO_0_0_tri_io[34]}]
set_property PACKAGE_PIN W12 [get_ports {GPIO_0_0_tri_io[35]}]
set_property PACKAGE_PIN R17 [get_ports {GPIO_0_0_tri_io[36]}]
set_property PACKAGE_PIN W15 [get_ports {GPIO_0_0_tri_io[37]}]
set_property PACKAGE_PIN AB17 [get_ports {GPIO_0_0_tri_io[38]}]
set_property PACKAGE_PIN Y12 [get_ports {GPIO_0_0_tri_io[39]}]
set_property PACKAGE_PIN Y13 [get_ports {GPIO_0_0_tri_io[40]}]
set_property PACKAGE_PIN V16 [get_ports {GPIO_0_0_tri_io[41]}]
set_property PACKAGE_PIN W16 [get_ports {GPIO_0_0_tri_io[42]}]
set_property PACKAGE_PIN AA17 [get_ports {GPIO_0_0_tri_io[43]}]
set_property PACKAGE_PIN Y17 [get_ports {GPIO_0_0_tri_io[44]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[44]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[40]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[41]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[42]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[43]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[39]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[38]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[37]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[36]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[35]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[34]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[33]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[29]}]

set_property PACKAGE_PIN D3 [get_ports {GPIO_0_0_tri_io[45]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[45]}]
set_property PACKAGE_PIN A4 [get_ports {GPIO_0_0_tri_io[46]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[46]}]
set_property PACKAGE_PIN F6 [get_ports {GPIO_0_0_tri_io[47]}]
set_property PACKAGE_PIN A6 [get_ports {GPIO_0_0_tri_io[48]}]
set_property PACKAGE_PIN E5 [get_ports {GPIO_0_0_tri_io[49]}]
set_property PACKAGE_PIN H3 [get_ports {GPIO_0_0_tri_io[50]}]
set_property PACKAGE_PIN C8 [get_ports {GPIO_0_0_tri_io[51]}]
set_property PACKAGE_PIN D8 [get_ports {GPIO_0_0_tri_io[52]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[47]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[48]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[49]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[50]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[51]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[52]}]
set_property PACKAGE_PIN C3 [get_ports {GPIO_0_0_tri_io[53]}]
set_property PACKAGE_PIN A5 [get_ports {GPIO_0_0_tri_io[54]}]
set_property PACKAGE_PIN G6 [get_ports {GPIO_0_0_tri_io[55]}]
set_property PACKAGE_PIN A7 [get_ports {GPIO_0_0_tri_io[56]}]
set_property PACKAGE_PIN F5 [get_ports {GPIO_0_0_tri_io[57]}]
set_property PACKAGE_PIN H4 [get_ports {GPIO_0_0_tri_io[58]}]
set_property PACKAGE_PIN B8 [get_ports {GPIO_0_0_tri_io[59]}]
set_property PACKAGE_PIN E8 [get_ports {GPIO_0_0_tri_io[60]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[60]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[59]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[58]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[57]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[56]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[55]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[54]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_0_0_tri_io[53]}]

set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[27]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[27]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[28]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[29]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[30]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[31]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[32]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[33]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[34]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[35]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[36]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[37]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[38]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[39]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[40]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[41]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[42]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[43]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[44]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[45]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[46]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[47]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[48]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[49]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[50]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[51]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[52]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[53]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[54]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[55]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[56]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[57]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[58]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[59]}]
set_property PULLDOWN true [get_ports {GPIO_0_0_tri_io[60]}]
